// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShServer;

namespace ServerWebApi.Migrations
{
    [DbContext(typeof(LppDatabaseContext))]
    partial class LppDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShServer.Models.LocationRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LocationRooms");
                });

            modelBuilder.Entity("ShServer.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AvgLevel");

                    b.Property<string>("BSSID");

                    b.Property<int?>("LocRommId");

                    b.Property<int>("LocationId");

                    b.Property<string>("LocationName");

                    b.Property<string>("SSID");

                    b.Property<double>("number_of_Mentions");

                    b.HasKey("Id");

                    b.HasIndex("LocRommId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("ShServer.Models.Log", b =>
                {
                    b.HasOne("ShServer.Models.LocationRoom", "LocRomm")
                        .WithMany("Logs")
                        .HasForeignKey("LocRommId");
                });
#pragma warning restore 612, 618
        }
    }
}
